apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: aq0kpwkgc-go
  janus-idp.io/tekton: aq0kpwkgc-go
  backstage.io/kubernetes-id: aq0kpwkgc-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: aq0kpwkgc-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
